version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: TechnicalSupport